# Generated by Django 3.2.5 on 2021-07-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='daily_rate',
            field=models.FloatField(),
            preserve_default=False,
        ),
    ]
