# Generated by Django 4.0.1 on 2022-01-13 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_daily_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='daily_rate',
            new_name='dailyRentalRate',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='number_in_stock',
            new_name='numberInStock',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_year',
        ),
    ]
